server:
  port: 3000
  base-url: /tareas_contexto
db:
  description: base de prueba
  host: localhost
  port: 5432
  database: tareas_contexto_db
  schema: tareas_contexto
  user: tareas_contexto_admin
  password: cambiar_esta_clave
install:
  dump:
    db:
      owner: tareas_contexto_owner
client-setup: 
  lang: es
devel:
  delay: 0
log:
  db:
    on-demand: true